/*
 * Calypte http://calypte.uoutec.com.br/
 * Copyright (C) 2018 UoUTec. (calypte@uoutec.com.br)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package br.com.uoutec.installer.painel.flow;

import br.com.uoutec.installer.ApplicationContext;
import br.com.uoutec.installer.entity.Configuration;
import br.com.uoutec.installer.entity.InstallerConfig;
import br.com.uoutec.installer.system.SystemType;
import br.com.uoutec.installer.painel.FlowPanel;
import br.com.uoutec.installer.painel.HeaderPanel;
import br.com.uoutec.installer.action.ServerInstanceInstallerAction;
import calypte.installer.action.entity.ServerInstance;

/**
 *
 * @author Ribeiro
 */
public class ServerInstancePainel extends HeaderPanel {

    public static final String SERVER_INSTANCE = "SERVER_INSTANCE";

    private ServerInstanceInstallerAction action;    
    
    public ServerInstancePainel() {
        super();
        this.action = new ServerInstanceInstallerAction();
    }

    public ServerInstancePainel(Configuration language) {
        super(language);
        this.action = new ServerInstanceInstallerAction();
    }
    
    @Override
    public void init(){
        this.initComponents();
        super.init();
    }
    
    @Override
    public boolean isSupported(){
        return 
            super.isSupported() && 
            SystemType.getCurrentSystemType().getSystemAction().isSupportedStartMenu();
    }
    
    @Override
    public void visible(FlowPanel flowPanel){
        super.visible(flowPanel);

        this.flowPanel.setDefaultButtonName(flowPanel.getLanguage().getValueProperty("button_next", "Next >"));
        this.flowPanel.setBackButtonName(flowPanel.getLanguage().getValueProperty("button_back", "< Back"));
        this.flowPanel.setCancelButtonName(flowPanel.getLanguage().getValueProperty("button_cancel", "Cancel"));
        
        this.jLabel2.setText(this.language.getValue(this.jLabel2.getText()));
        this.jLabel3.setText(this.language.getValue(this.jLabel3.getText()));
        this.jLabel4.setText(this.language.getValue(this.jLabel4.getText()));
        this.jLabel5.setText(this.language.getValue(this.jLabel5.getText()));
        
        this.jRadioButton1.setText(this.language.getValue(this.jRadioButton1.getText()));
        this.jRadioButton2.setText(this.language.getValue(this.jRadioButton2.getText()));
        this.jRadioButton3.setText(this.language.getValue(this.jRadioButton3.getText()));
        
        this.flowPanel.setDefaultButtonVisible(true);
        this.flowPanel.setCancelButtonVisible(true);
        this.flowPanel.setBackButtonVisible(true);
        
        this.setTitleHeader(this.language.getValueProperty("title"));
        this.setSubTitleHeader(this.language.getValueProperty("sub_title"));
    }

    @Override
    public void hidden(FlowPanel flowPanel){
        super.hidden(flowPanel);
        InstallerConfig installerConfig = ApplicationContext.getInstallerConfig();
        
        installerConfig.getPackage("Default").removeItem(this.action, null, null);
        installerConfig.getPackage("Default").addItem(this.action, true, null, null);
        
        if(jRadioButton1.isSelected()){
            this.action.setServerInstance(ServerInstance.DEVELOPER);
        }
        else
        if(jRadioButton2.isSelected()){
            this.action.setServerInstance(ServerInstance.SERVER);
        }
        else
        if(jRadioButton3.isSelected()){
            this.action.setServerInstance(ServerInstance.DEDICATED_SERVER);
        }
        
    }
    
    @Override
    public String getReadyMessage(){
        
        StringBuilder b = new StringBuilder();
        b
            .append("<p>Instance type:</p>")
            .append("<p>&nbsp;&nbsp;&nbsp;&nbsp;").append(this.action.getServerInstance()).append("</p>");
        return this.language.getValue(b.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 250));

        jLabel2.setText("<html><body>{developer_desc}</body></html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLabel2);
        jLabel2.setBounds(60, 120, 490, 40);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("<html><body>{developer_title}</body></html>");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1);
        jRadioButton1.setBounds(40, 90, 290, 25);

        jLabel3.setText("<html><body>{text_title}</body></html>");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel3);
        jLabel3.setBounds(40, 60, 530, 20);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("<html><body>{server_title}</body></html>");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2);
        jRadioButton2.setBounds(40, 160, 290, 25);

        jLabel4.setText("<html><body>{server_desc}</body></html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLabel4);
        jLabel4.setBounds(60, 190, 490, 40);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("<html><body>{dedicated_server_title}</body></html>");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3);
        jRadioButton3.setBounds(40, 230, 290, 25);

        jLabel5.setText("<html><body>{dedicated_server_desc}</body></html>");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLabel5);
        jLabel5.setBounds(60, 260, 480, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
